# Generated by Django 3.2.6 on 2023-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_employee_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.CharField(choices=[('JN', 'Junior'), ('MD', 'Middle'), ('SN', 'Senior'), ('TL', 'Team lead')], default='JN', max_length=2),
            preserve_default=False,
        ),
    ]
